dist: trusty
sudo: falsegit
language: node_js
node_js:
- 7
before_script:
    - "sh -e /etc/init.d/xvfb start"
    - "export DISPLAY=:99.0"
    - jdk_switcher use oraclejdk8
addons:
  firefox: "52.0"
